heat_template_version: 2013-05-23

description: |
  This is a Heat template to deploy a single Linux server running Durpal.

parameter_groups:

- label: Server Settings
  parameters:
  - server_hostname
  - image
  - flavor

- label: DrupalSettings
  parameters:
  - domain
  - username

- label: rax-dev-params
  # These are parameters that will not be displayed in the portal. The purpose
  # of these parameters are for users who are developing or testing newer or
  # different setups. If any of these parameters are changed, there is a good
  # chance this stack will fail to properly deploy.
  parameters:
  - kitchen
  - chef_version
  - version
  - prefix

parameters:

  # Server settings
  server_hostname:
    label: Server Name
    description: Hostname to use for the server that's built.
    type: string
    default: Drupal
    constraints:
    - length:
        min: 1
        max: 64
    - allowed_pattern: "^[a-zA-Z][a-zA-Z0-9-]*$"
      description: |
        Must begin with a letter and contain only alphanumeric characters.

  image:
    label: Operating System
    description: |
      Required: Server image used for all servers that are created as a part of
      this deployment.
    type: string
    default: Ubuntu 12.04 LTS (Precise Pangolin)
    constraints:
    - allowed_values:
      - Ubuntu 12.04 LTS (Precise Pangolin)
      description: Must be a supported operating system.

  flavor:
    label: Server Size
    description: |
      Required: Rackspace Cloud Server flavor to use. The size is based on the
      amount of RAM for the provisioned server.
    type: string
    default: 4 GB Performance
    constraints:
    - allowed_values:
      - 1 GB Performance
      - 2 GB Performance
      - 4 GB Performance
      - 8 GB Performance
      - 15 GB Performance
      - 30 GB Performance
      - 1GB Standard Instance
      - 2GB Standard Instance
      - 4GB Standard Instance
      - 8GB Standard Instance
      - 15GB Standard Instance
      - 30GB Standard Instance
      description: |
        Must be a valid Rackspace Cloud Server flavor for the region you have
        selected to deploy into.

  # Durpal settings
  domain:
    label: Site Domain
    description: Domain to be used with Drupal site
    type: string
    default: "example.com"
    constraints:
    - allowed_pattern: "^[a-zA-Z0-9.-]{1,255}.[a-zA-Z]{2,15}$"
      description: Must be a valid domain name

  version:
    label: Drupal Version
    description: Version of Drupal to install
    type: string
    default: "7.31"
    constraints:
    - allowed_values:
      - "7.31"
      - "6.33"

  # Database and system user configuration
  prefix:
    label: Database Prefix
    description: Prefix to use for Drupal database tables
    type: string
    default: drupal_
    constraints:
    - allowed_pattern: "^[0-9a-zA-Z$_]{0,10}$"
      description: |
        Prefix must be shorter than 10 characters, and can only include
        letters, numbers, $, and/or underscores.

  database_name:
    label: Database Name
    description: Drupal database name
    type: string
    default: drupal
    constraints:
    - allowed_pattern: "^[0-9a-zA-Z$_]{1,64}$"
      description: |
        Maximum length of 64 characters, may only contain letters, numbers, and
        underscores.

  username:
    label: Username
    description: "Username for system, database, and Drupal logins."
    type: string
    default: drupal_user
    constraints:
    - allowed_pattern: "^(.){1,16}$"
      description: |
        Must be shorter than 16 characters, this is due to MySQL's maximum
        username length.

  kitchen:
    label: Kitchen URL
    description: "URL for a git repo containing required cookbooks"
    type: string
    default: https://github.com/rackspace-orchestration-templates/drupal-single.git

  chef_version:
    label: Chef Version
    description: Version of chef client to use
    type: string
    default: 11.14.2

resources:
  # Random password generation
  database_password:
    type: "OS::Heat::RandomString"
    properties:
      length: 16
      sequence: lettersdigits

  mysql_root_password:
    type: "OS::Heat::RandomString"
    properties:
      length: 16
      sequence: lettersdigits

  mysql_repl_password:
    type: "OS::Heat::RandomString"
    properties:
      length: 16
      sequence: lettersdigits

  mysql_debian_password:
    type: "OS::Heat::RandomString"
    properties:
      length: 16
      sequence: lettersdigits

  # Random strings for WP salting
  drupal_auth:
    type: "OS::Heat::RandomString"
    properties:
      length: 32
      sequence: hexdigits

  drupal_logged_in:
    type: "OS::Heat::RandomString"
    properties:
      length: 32
      sequence: hexdigits

  drupal_nonce:
    type: "OS::Heat::RandomString"
    properties:
      length: 32
      sequence: hexdigits

  drupal_secure_auth:
    type: "OS::Heat::RandomString"
    properties:
      length: 32
      sequence: hexdigits

  # SSH KEYS
  sync_key:
    type: "OS::Nova::KeyPair"
    properties:
      name:
        str_replace:
          template: "%stack_id%-sync"
          params:
            "%stack_id%": { get_param: "OS::stack_id" }
      save_private_key: true

  ssh_key:
    type: "OS::Nova::KeyPair"
    properties:
      name: { get_param: "OS::stack_id" }
      save_private_key: true

  # Server resources
  drupal_server:
    type: "Rackspace::Cloud::Server"
    properties:
      name: { get_param: server_hostname }
      flavor: { get_param: flavor }
      image: { get_param: image }
      key_name: { get_resource: ssh_key }
      metadata:
        rax-heat: { get_param: "OS::stack_id" }

  # Chef resources
  drupal_setup:
    type: "OS::Heat::ChefSolo"
    depends_on: drupal_server
    properties:
      username: root
      private_key: { get_attr: [ssh_key, private_key] }
      host: { get_attr: [drupal_server, accessIPv4] }
      kitchen: { get_param: kitchen }
      chef_version: { get_param: chef_version }
      node:
        apache:
          timeout: 30
          serversignature: "Off"
          traceenable: "Off"
        hollandbackup:
          main:
            backup_directory: "/var/lib/mysqlbackup"
            mysqldump:
              user: "root"
              host: "localhost"
              password: { get_attr: [mysql_root_password, value] }
        mysql:
          server_root_password: { get_attr: [mysql_root_password, value] }
          server_repl_password: { get_attr: [mysql_repl_password, value] }
          server_debian_password: { get_attr: [mysql_debian_password, value] }
          remove_test_database: true
          remove_anonymous_users: true
        drupal:
          version: { get_param: version }
          dir:
            str_replace:
              template: "/var/www/vhosts/%domain%"
              params:
                "%domain%": { get_param: domain }
          db:
            name: { get_param: database_name }
            user: { get_param: username }
            pass: { get_attr: [database_password, value] }
            host: "127.0.0.1"
          admin: { get_param: username }
          pass: { get_attr: [database_password, value] }
        rax:
          firewall:
            tcp: [80]
        run_list: ["recipe[apt]",
                   "recipe[drupal]",
                   "recipe[hollandbackup]",
                   "recipe[hollandbackup::mysqldump]",
                   "recipe[hollandbackup::main]",
                   "recipe[hollandbackup::backupsets]",
                   "recipe[hollandbackup::cron]",
                   "recipe[rax-firewall]"]

outputs:
  private_key:
    description: SSH Private Key
    value: { get_attr: [ssh_key, private_key] }

  server_ip:
    description: Server IP
    value: { get_attr: [drupal_server, accessIPv4] }

  drupal_user:
    description: Drupal User
    value: { get_param: username }

  drupal_password:
    description: Dupal Password
    value: { get_attr: [database_password, value] }

  mysql_root_password:
    description: MySQL Root Password
    value: { get_attr: [mysql_root_password, value] }
